    version: "3"
    services:
        web:
            restart: always
            network_mode: host
            build: .
            volumes:
               - ./:/test_project
            expose:
               - '8000'
            depends_on:
               - db
            command: python manage.py runserver 0.0.0.0:8000
        db:
            network_mode: host
            restart: always
            image: postgres:latest
            expose:
                - '5432'
            environment:
                - POSTGRES_USER=admin
                - POSTGRES_PASSWORD=qwerty12345
                - POSTGRES_DB=docker_test_db