# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('create_date', models.DateField(auto_now=True)),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
